<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.17" />
    <PackageReference Include="AutoMapper" Version="8.0.0" />
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="Serilog" Version="3.0.1" />
  </ItemGroup>
</Project>
