<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Polly" Version="8.3.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.18" />
    <PackageReference Include="MediatR" Version="9.0.0" />
  </ItemGroup>

</Project>
