<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Dapper" Version="2.0.0" />
    <PackageReference Include="Npgsql" Version="5.0.17" />
    <PackageReference Include="FluentValidation" Version="11.9.0" />
  </ItemGroup>

</Project>
